services:
  postgres:
    image: postgres:17
    # ports:
    #   - "${DB_PORT}:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres-data:
    name: postgres-data